### ISSUE TITLE
SignedNFTAttestation does not verify key used to sign it

### ISSUE THREAD

**Issue by jot2re** [TokenScript/attestation#200]
Currently `SignedNFTAttestation` does not validate that the key that is used to sign with, is also the key attested to in the `SignedIdentifierAttestation`.
It seems we definitely want to ensure that the key used to sign the NFTAttestation is the one used attested to.
Even though this part of the code is probably not in use this issue might also be in the JS code.

**Comment by JamesSmartCell** [comment]
Hi @jot2re sorry for the delay, yes the way I approached this was to use the address in the base IdentifierAttestation and test the integrity of this address by performing verify on the SignedIdentifierAttestation. The SignedNFTAttestation then must correspond to the subject in the IdentifierAttestation because you need to verify the integrity of that signature and unwrap like a cryptographic Matryoshka.
