### ISSUE TITLE
Avoid need to connect wallet additionally from attestation.id modal

### ISSUE THREAD

**Issue by AW-STJ** [TokenScript/attestation#229]
For Liscon NFT generation example, it was discovered that user would have to connect wallet when the attestation.id modal is displayed. 

It is best to avoid this, as user would have already connected the wallet to the site on which the attestation.id modal is displayed. Is there any way to resolve this multiple connection prompts? Keen to hear your thoughts - @oleggrib @nicktaras @foxgem

**Comment by oleggrib** [comment]
We had an idea to send object from attestation.id to the Requestor Site (RS) and sign it on the RS. But we decided to sign attestRequest message on the attestation.id (AI) because user can be confused if RS ask user for attestation.

I suggest to send all messages for sign to the Token Origin Website (TOW), its devcon-tickets in our test case. It will have more authority than RS. 
TOW domain separated from RS and RS malicious scripts don't have access to the TOW content, so secrets will be secured by browser.

We only need to open AI tab to enter One Time Password for Email (OTP), its optional, because OTP also can be entered to the RS form by Negotiator.

So we can allow signing all messages to the TOW and open AI tab one time to generate and send data to the AI backend and save attestation+secret in the user browser for use with another APPs.

We can skip to open AI tab and generate RequestAttest and read OTP directly on the TOW and save attestation in Local Storage under TOW domain, but in that case user have to generate new attestation for each token, but when AI will be popular enough then it will be not user friendly. So better open new tab for 1 second than ask user to sign additional message.

@jot2re , @colourful-land , @JamesSmartCell , what can you say?
cc @AW-STJ @nicktaras @foxgem

Solutions like that one require Weiwu's approval, this is why I assigned that issue to the Weiwu.

**Comment by jot2re** [comment]
I think there might be an issue of TOW hijacking the user's attestation. Since TOW learns OTP that has been sent to the user's email, they could construct and sign a RequestAttest to their own Ethereum key, thus being able to claim ownership of the user's email to any party relying on AI.
But I might be misunderstanding part of the flow?

**Comment by oleggrib** [comment]
TOW is a page with access to ticket+ticketSecret + attestation + attestationSecret, because TOW constructs proofOfSecrets. So hijacking of TOW can be a problem. 
Anyway we require some page to receive all the data+secrets togather and construct proof and that page can be hacked.

**Comment by jot2re** [comment]
Ah, I see. But this issue of TOW learning the OTP to get an attestation issued is different.
TOW knowing token+tokenSecret + attestation + attestationSecret _only_ allows it to use the token, which it itself issued and hence, per this [discussion](https://github.com/TokenScript/token-negotiator/issues/121), is not really a big issue.
TOW knowing token+tokenSecret + attestation + attestationSecret does _not_ allow it to e.g. construct proofs with a wrong email in the attestation or change the Ethereum address that is attested to, in the attestation. 

The issue is if the attestation is issued as part of the flow, where TOW learns the OTP that is supposed to allow the user to get an attestation issued. In this case the TOW could use the OTP to pretend to own the user's email and get an attestation for the user's email, linked to TOW's Ethereum key.
This breaks the security model separating the responsibility and capabilities of TOW and AI.

**Comment by oleggrib** [comment]
I think its related to implementation. if AI create session with session_token and stay session alive and limit invalid OTP number per session then its should not be a security problem if TOW send USER_EMAIL to AI and after thet send OTP to AI (in same secured session). 

We just have to limit brutforces.   

If its:
- in the user browser 
- user entered email (or email received from other APP)
- user sign wallet EIP712 message (message includes email), AI creates session_token
- OTP verification limited with session_token

then all the actions still in the user browser and user have to sign attestaRequest (per session), so doesnt matter what browser tab read USER_EMAIL and OTP

**Comment by foxgem** [comment]
> if AI create session with session_token and stay session alive

Keep the whole server stateless is by design, so there is no session.

**Comment by jot2re** [comment]
Ah, I see what you mean.
If we ensure that the user signs the RequestAttestation and sends it to AI _before_ the OTP is issued, then we avoid the issue.

**Comment by oleggrib** [comment]
> > if AI create session with session_token and stay session alive
> 
> Keep the whole server stateless is by design, so there is no session.

I mean custom session between browser tabs, sorry that I didnt mention that before.

**Comment by jot2re** [comment]
> > if AI create session with session_token and stay session alive
> 
> Keep the whole server stateless is by design, so there is no session.

**Comment by jot2re** [comment]
I realised I was a bit too quick with my reply here: if _both_ the OTP _and_ the AttestationRequest goes through TOW then they can execute a man-in-the-middle attack and basically get a certificate issued towards the user's email but based on their Ethereum key.
It is strictly needed that _either_ the AttestationRequest is supplied (first!) directly to attestation.id or that the OTP is supplied to attestation.id.
@oleggrib do you agree?

**Comment by oleggrib** [comment]
yes, correct. man-in-the-middle attack possible in that case.
in case when we create/sign on AI website then we must make secure single website (AI), but in case of TOW anyone can make own token and each of them have a chance to be hacked/script_injected and hacked one can create attestation with user email and wrongWalletAddress.

that problem can happen even if we create attestRequest on the TOW, but enter OTP to the AI.

so current flow is secured (except of issue with validate OTP) and we can't move all signatures to the AI.
AI can be third-party service, so it can work separately from Tickets/etc.

What can we do to improve user experience is - send with postMessage wallet name to use. in that case we can avoid user to select same wallet again and it will avoid problen when user sign attestation with one wallet, but use another walletaddress for other actions.

@foxgem , @jot2re , what do you think?
cc @AW-STJ

**Comment by jot2re** [comment]
I agree, except that I believe it is possible to avoid the issue if AttestationRequest is relayed through TOW _and_ OTP is entered directly at attestation.id. The reason is that the OTP can be constructed such that it is linked to AttestationRequest and hence resupplying AttestationRequest to attestation.id, along with the OTP, allow attestation.id to validate that OTP is correct _and_ AttestationRequest is the same as the AttestationRequest used to generate the OTP (and hence that TOW has not injected an AttestationRequest to a wrongWalletAddress). 

However if we are already planning on still going through attestation.id for the entire attestation issuance (which seems to be necessary for security) then it is a non-issue in any case :)

@oleggrib If I understand your suggestion with postMessage correctly you mean we still do everything through attestation.id, but simply use the postMessage to avoid the user having to select the correct wallet again, and thus make the flow lighter for the user, right?

**Comment by jot2re** [comment]
> I agree, except that I believe it is possible to avoid the issue if AttestationRequest is relayed through TOW _and_ OTP is entered directly at attestation.id. The reason is that the OTP can be constructed such that it is linked to AttestationRequest and hence resupplying AttestationRequest to attestation.id, along with the OTP, allow attestation.id to validate that OTP is correct _and_ AttestationRequest is the same as the AttestationRequest used to generate the OTP (and hence that TOW has not injected an AttestationRequest to a wrongWalletAddress).
> 

With the discussion and solution [here](https://github.com/AlphaWallet/attestation.id/issues/119) it is not possible to link the OTP to the AttestationRequest as I discussed above. 
In this situation I cannot see other solutions than to require AttestationRequest and OTP validation happening on the attestation.id domain.

**Comment by micwallace** [comment]
@oleggrib @jot2re This is exactly the problem I am trying to solve for token-negotiator. Performing all signing in either AI or TOW is the way to go. Has there been any decision on the best place to do it? It will simplify the process if we do it in AI, but is that making TN overly dependent on AI?

**Comment by jot2re** [comment]
> @oleggrib @jot2re This is exactly the problem I am trying to solve for token-negotiator. Performing all signing in either AI or TOW is the way to go. Has there been any decision on the best place to do it? It will simplify the process if we do it in AI, but is that making TN overly dependent on AI?

I am not sure there is a final decision. My colleague and I just finished a full security review of the process and code (@AW-STJ can share it with you) where we discuss this and connected issues. But I think the best is to have a meeting discussion this and the other issues in the security report to figure out exactly which way we wanna go.

However, I think the overall best solution is to do the signing in AI, and if needed link this to the a a ticket usage by using it as part of the nonce in ZK proof.

**Comment by oleggrib** [comment]
We can have problems when we try to use single wallet for multiple domains. 
Especially when we use hardware wallets.

in case of Ledger Live windows app it allow to connect single domain at the moment. So in case if we use some ON-chain tokens then Ledger have to connect to the attestation.id (to sign attestaRequest) and to the HotelBogota (to sign transaction).
Ledger App dont allow to disconnect wallet programmatically, use have to understand that he need to click "disconnect" and after than click "connect", but its not obvious. So better ( if possible ) to send sign requests to the single browser tab (or use as less as possible tabs).  

If we still have to use multiple tabs then better limit wallets to Metamask or AlphaWallet (when it will be ready as browser extension). Metamask can connect Ledger directly and can work flexible enough.

@micwallace , @AW-STJ , @nicktaras , @jot2re

**Comment by micwallace** [comment]
I really think WalletConnect should be working for the entire process, as browser wallet may not be delivered for a while. On Friday I re-implemented message handling that was defined in authenticator.js into TN. So error messages and requests to show iframe modal can be returned to the parent frame/s. I think if possible we should definitely avoid using multiple tabs for wallet communication. 

There is plenty to discuss from @jot2re's report, so I second the call to have a meeting to go through everything and come up with a full action plan to address the issues.

@oleggrib  , @AW-STJ , @nicktaras , @jot2re

**Comment by micwallace** [comment]
Yep @oleggrib I can see the benefit of doing all signing from AI, keep it the trusted authority for all wallet actions. 

There is plenty to discuss from @jot2re's report, so I second the call to have a meeting to go through everything and come up with an action plan.

**Comment by oleggrib** [comment]
I think we can close this issue, because:
- attestation.id require to connect wallet, in most cases its WalletConnect, so we have to display attestation.id window
- attestation.id is separate product, we cant send data to sign to the attestation.id
- products must be secure, so each wallet connection display user domain, which app want to use and better avoid confuse users. 

so in our case no secure way to save wallet connect requsts.
@AW-STJ , are you agree, can we close issue?

**Comment by AW-STJ** [comment]
Thanks Oleh, agreed. May be the way to avoid user confusion is to open up a new tab rather than doing it through a modal. Closing the issue as we have discovered that the users will have to connect the wallet again through modal.
