### ISSUE TITLE
Write a smart contract MVP that handles email attestation mock ups

### ISSUE THREAD

**Issue by James-Sangalli** [TokenScript/attestation#29]
as specified here: https://github.com/AlphaWallet/blockchain-attestation/blob/master/use-cases/send-ether-by-identifier-attestation.md

- [ ] expand on the 2018 code to take the now formalised attestation
- [ ] expand on it to take the Cheque (test case pending from Tore)
- [ ] make the smart contract verify the Schnorr zk-proof of knowledge submitted in the redeeming transaction.

**Comment by colourful-land** [comment]
Yes, there is already a half-baked one but there hadn't been github issue to track that work.

**Comment by colourful-land** [comment]
@JamesSmartCell Tore has a new branch building on top of the Attestation code (implementing the Signable interface). This can be found in the branch attestation-addition: https://github.com/AlphaWallet/alpha-wallet-android/tree/attestation-additions/lib/src/main/java/com/alphawallet/attestation 
This code includes a [.pem file which contains a signed attestation with secp256k1](https://github.com/AlphaWallet/alpha-wallet-android/blob/attestation-additions/lib/src/test/java/com/alphawallet/attestation/signedAtt.pem ) (he wrote a test-case that constructs such a gem). Can you expand on [the code wrote in 2018](https://github.com/AlphaWallet/blockchain-attestation/pull/30) to take the whole gem?

**Comment by colourful-land** [comment]
we had a smart contract MVP project planning meeting last evening at 7pm. @Soylentblue  will shoulder the majority of the work again which will take 2~3 weeks (I feel we can make it even shorter if lucky, e.g. that the assembly code for verifying zk-proof just works). He is able to start mid-week next week and Tore has already produced the whole smart contract code in Java so the work is porting it to solidity and discard the Java smart contract as scaffolding.

**Comment by colourful-land** [comment]
@JamesSmartCell With the [latest commit](https://github.com/AlphaWallet/alpha-wallet-android/commit/8e16c6dd9468c0b964c16ee4031e62e3c8cd1f80) now you can get a .der file. Try run the test case:

https://github.com/AlphaWallet/alpha-wallet-android/blob/8e16c6dd9468c0b964c16ee4031e62e3c8cd1f80/lib/src/test/java/com/alphawallet/attestation/TestAttestation.java#L58

You will get:

````
To check the unsigned X509 attestation, run this:
$ openssl asn1parse -inform DER -in /tmp/unsigned_x5092092332850498924027.der
````
By the way you can upload the file to https://lapo.it/asn1js/ sparing you to use openssl commandline, but apparently I can't include that in the test case, since openly recommending one to share attestation on the Internet is bad advice.

**Comment by James-Sangalli** [comment]
@colourful-land closed by https://github.com/AlphaWallet/blockchain-attestation/pull/34?

**Comment by colourful-land** [comment]
Yes but continues to #35 to drive down the cost of using.
