### ISSUE TITLE
AttestorTest > testSunshine() FAILED with JDK15

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/attestation#82]
I have got gradle test failed on win10 (JDK 15)
> Task :test

AttestorTest > testSunshine() FAILED
    org.bouncycastle.operator.RuntimeOperatorException at AttestorTest.java:84
        Caused by: java.security.SignatureException at AttestorTest.java:84
            Caused by: java.security.InvalidAlgorithmParameterException at AttestorTest.java:84

79 tests completed, 1 failed

> Task :test FAILED

I attached test report
[dk.alexandra.trulioo.issuer.AttestorTest.zip](https://github.com/TokenScript/attestation/files/5764710/dk.alexandra.trulioo.issuer.AttestorTest.zip)

**Comment by colourful-land** [comment]
Looks like this issue is specific to JDK15 - we didn't exeriene it because I used JDK14 and James Brown JDK11
https://seanjmullan.org/blog/2020/10/13/jdk15


--

## The native elliptic curves have been disabled by default

The elliptic curves that are implemented in native C code in the SunEC provider have been disabled by default. These curves are no longer recommended and/or are not implemented using modern formulas and techniques. APIs that try to use one of these curves will throw an Exception with the message “Legacy SunEC curve disabled” and the name of the curve.

To re-enable them (at your own risk), set the jdk.sunec.disableNative system property to false. For example:

    $ java -Djdk.sunec.disableNative=false ...

Note however, that if you re-enable them, they are still disabled by default when used in TLS, CertPath, or Signed JARs. See the JDK 14 release note for more information.

The curves that are disabled by this change are:

secp112r1, secp112r2, secp128r1, secp128r2, secp160k1, secp160r1,
secp160r2, secp192k1, secp192r1, secp224k1, secp224r1, secp256k1,
sect113r1, sect113r2, sect131r1, sect131r2, sect163k1, sect163r1,
sect163r2, sect193r1, sect193r2, sect233k1, sect233r1, sect239k1,
sect283k1, sect283r1, sect409k1, sect409r1, sect571k1, sect571r1,
X9.62 c2tnb191v1, X9.62 c2tnb191v2, X9.62 c2tnb191v3, X9.62 c2tnb239v1,
X9.62 c2tnb239v2, X9.62 c2tnb239v3, X9.62 c2tnb359v1, X9.62 c2tnb431r1,
X9.62 prime192v2, X9.62 prime192v3, X9.62 prime239v1, X9.62 prime239v2,
X9.62 prime239v3, brainpoolP256r1 brainpoolP320r1, brainpoolP384r1,
brainpoolP512r1

The following curves are implemented in Java, use modern techniques, and are not affected by this change: secp256r1, secp384r1, secp521r1, x25519, x448, ed25519, and ed448.

**Comment by jot2re** [comment]
So it seems to only be an issue int he Trulioo specific code. Basically it seems that the issue is that even though we use BC for the ECDSA crypto, when we verify a certificate it makes a call to the underlying standard Java code to verify the signature and hence it fails in Java 15. I can try to see if there is a way to force this to be verified using only BC's implementation of ECDSA. I suspect this could fix the issue.

**Comment by jot2re** [comment]
I have fixed this in PR #84
